# Generated by Django 4.2.2 on 2023-12-15 18:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='Posts')),
                ('shortdesc', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=600)),
                ('created_on', models.DateField(default=datetime.date.today)),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=200)),
                ('commented_by', models.ForeignKey(db_column='commented_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(db_column='cid', on_delete=django.db.models.deletion.CASCADE, to='blogapp.posts')),
            ],
        ),
    ]
