# Generated by Django 4.2.2 on 2023-12-13 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2023, 12, 13, 15, 56, 51, 29877)),
        ),
    ]
