# Generated by Django 4.2.2 on 2023-12-13 17:05

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_posts_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='uid',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2023, 12, 13, 22, 33, 53, 71822)),
        ),
    ]
