# Generated by Django 4.2.2 on 2023-12-14 17:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0003_posts_uid_alter_posts_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='post',
            new_name='description',
        ),
        migrations.AddField(
            model_name='comments',
            name='created_by',
            field=models.CharField(default=2023, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='img',
            field=models.ImageField(default=1, upload_to='Posts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='shortdesc',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_on',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='posts',
            name='uid',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
